name: MongoDB Ping Test

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  ping-mongodb:
    runs-on: ubuntu-latest
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run:  pip install pymongo
      - name: Ping MongoDB
        run: python connectdb.py
